dashboardApp.controller('dashController', ['$scope', function ($scope) {
  $scope.exampleQuestions = [
      {"Question": "What is db Impresa eXtra?", "Answer":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse fermentum eros id lorem placerat ultrices. Duis dolor velit, sodales in lacinia ut, semper quis nisi. Fusce fermentum leo vitae convallis consequat. Vivamus gravida felis id dolor feugiat fermentum. Etiam non arcu non neque cursus convallis at gravida purus. Nam a mollis massa. Vestibulum maximus at ligula euismod laoreet. Sed eget eros velit."},
      {"Question": "Who can get db Impresa eXtra?", "Answer":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse fermentum eros id lorem placerat ultrices. Duis dolor velit, sodales in lacinia ut, semper quis nisi. Fusce fermentum leo vitae convallis consequat. Vivamus gravida felis id dolor feugiat fermentum. Etiam non arcu non neque cursus convallis at gravida purus. Nam a mollis massa. Vestibulum maximus at ligula euismod laoreet. Sed eget eros velit."},
      {"Question": "How can i create a Impresa eXtra?", "Answer":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse fermentum eros id lorem placerat ultrices. Duis dolor velit, sodales in lacinia ut, semper quis nisi. Fusce fermentum leo vitae convallis consequat. Vivamus gravida felis id dolor feugiat fermentum. Etiam non arcu non neque cursus convallis at gravida purus. Nam a mollis massa. Vestibulum maximus at ligula euismod laoreet. Sed eget eros velit."},
      {"Question": "How can get db Impresa eXtra?", "Answer":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse fermentum eros id lorem placerat ultrices. Duis dolor velit, sodales in lacinia ut, semper quis nisi. Fusce fermentum leo vitae convallis consequat. Vivamus gravida felis id dolor feugiat fermentum. Etiam non arcu non neque cursus convallis at gravida purus. Nam a mollis massa. Vestibulum maximus at ligula euismod laoreet. Sed eget eros velit."},
      {"Question": "How much does it cost for a paid account?", "Answer":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse fermentum eros id lorem placerat ultrices. Duis dolor velit, sodales in lacinia ut, semper quis nisi. Fusce fermentum leo vitae convallis consequat. Vivamus gravida felis id dolor feugiat fermentum. Etiam non arcu non neque cursus convallis at gravida purus. Nam a mollis massa. Vestibulum maximus at ligula euismod laoreet. Sed eget eros velit."},
      {"Question": "How can i play?", "Answer":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse fermentum eros id lorem placerat ultrices. Duis dolor velit, sodales in lacinia ut, semper quis nisi. Fusce fermentum leo vitae convallis consequat. Vivamus gravida felis id dolor feugiat fermentum. Etiam non arcu non neque cursus convallis at gravida purus. Nam a mollis massa. Vestibulum maximus at ligula euismod laoreet. Sed eget eros velit."},
      {"Question": "How can i subscribe to?", "Answer":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse fermentum eros id lorem placerat ultrices. Duis dolor velit, sodales in lacinia ut, semper quis nisi. Fusce fermentum leo vitae convallis consequat. Vivamus gravida felis id dolor feugiat fermentum. Etiam non arcu non neque cursus convallis at gravida purus. Nam a mollis massa. Vestibulum maximus at ligula euismod laoreet. Sed eget eros velit."},
      {"Question": "What is a Unique Access Code?", "Answer":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse fermentum eros id lorem placerat ultrices. Duis dolor velit, sodales in lacinia ut, semper quis nisi. Fusce fermentum leo vitae convallis consequat. Vivamus gravida felis id dolor feugiat fermentum. Etiam non arcu non neque cursus convallis at gravida purus. Nam a mollis massa. Vestibulum maximus at ligula euismod laoreet. Sed eget eros velit."},
      {"Question": "My Unique Access Code  doesn't work", "Answer":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse fermentum eros id lorem placerat ultrices. Duis dolor velit, sodales in lacinia ut, semper quis nisi. Fusce fermentum leo vitae convallis consequat. Vivamus gravida felis id dolor feugiat fermentum. Etiam non arcu non neque cursus convallis at gravida purus. Nam a mollis massa. Vestibulum maximus at ligula euismod laoreet. Sed eget eros velit."},
      {"Question": "Who should i contact if i need help?", "Answer":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse fermentum eros id lorem placerat ultrices. Duis dolor velit, sodales in lacinia ut, semper quis nisi. Fusce fermentum leo vitae convallis consequat. Vivamus gravida felis id dolor feugiat fermentum. Etiam non arcu non neque cursus convallis at gravida purus. Nam a mollis massa. Vestibulum maximus at ligula euismod laoreet. Sed eget eros velit."},
      {"Question": "What are the operating system requirements?", "Answer":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse fermentum eros id lorem placerat ultrices. Duis dolor velit, sodales in lacinia ut, semper quis nisi. Fusce fermentum leo vitae convallis consequat. Vivamus gravida felis id dolor feugiat fermentum. Etiam non arcu non neque cursus convallis at gravida purus. Nam a mollis massa. Vestibulum maximus at ligula euismod laoreet. Sed eget eros velit."},
      {"Question": "Feedback and complaints?", "Answer":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse fermentum eros id lorem placerat ultrices. Duis dolor velit, sodales in lacinia ut, semper quis nisi. Fusce fermentum leo vitae convallis consequat. Vivamus gravida felis id dolor feugiat fermentum. Etiam non arcu non neque cursus convallis at gravida purus. Nam a mollis massa. Vestibulum maximus at ligula euismod laoreet. Sed eget eros velit."}
    ]

}]);